apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app-container
        image: 892139891520.dkr.ecr.eu-west-2.amazonaws.com/quiz-app-repo
        ports:
          - containerPort: 3000
